### PR TITLE
Remove resolutions like 1920_1080 or 1920-1080

### PR DESCRIPTION
**Pull request by Leslie-Wong-H**
Counter examples:

image

### CODE REVIEW

**Comment by soruly** [comment]
I do notice there's such an ambiguous case.
Unfortunately, I can't think of any way to tell if the number is an episode or resolution.
I'd just rename the files :S

**Comment by Leslie-Wong-H** [comment]
The scenario is that the faulty record had been indexed to the production system and is hard to erase, acting like a tar pit (from _The Mythical Man-Month_) to crash the whole site when its frames get searched. 

I came up with another way to resolve this. 

Inspecting the source code of aniep, I noticed the statement to remove resolutions like 720 or 1080 is not sufficient. 

```js
  filename = filename.replace(/(?:1920|1080|1280|720|1024|576)(?:p|P|x|X|×)/, "x"); // remove resolutions like 720 or 1080
```

When it faces "1280x720" but not "(1280x720)", the result is "x720", remaining the unwanted "720" that may cause an error.

What is lacking is that it performs the reg verification the forward way and misses to check the latter number of "1280x720".

The resolution: 
`Add reg lookbehind verification after the reg forward verification`

```js
  filename = filename.replace(/(?:1920|1080|1280|720|1024|576)(?:p|P|x|X|×)/, "x"); // remove resolutions like 720 or 1080 the forward way
  filename = filename.replace(/(?<=x|X|×)(?:1920|1080|1280|720|1024|576)/, "x"); // remove resolutions like 720 or 1080 the lookbehind way
```

In this way, the result of "1280x720" is "x". No doubt. 

And the case of "1920_1080" or "1920-1080" can be done by simply declaring `(?:p|P|x|X|×|_|-)` and `(?<=x|X|×|_|-)`.

```js
  filename = filename.replace(/(?:1920|1080|1280|720|1024|576)(?:p|P|x|X|×|_|-)/, "x"); // remove resolutions like 720 or 1080 the forward way
  filename = filename.replace(/(?<=x|X|×|_|-)(?:1920|1080|1280|720|1024|576)/, "x"); // remove resolutions like 720 or 1080 the lookbehind way
```

Elegant and unified. 

image

You are welcome to merge. :)

**Comment by soruly** [comment]
There's a case in `[XFSUB][Naruto Shippuuden][640_420][BIG5][x264 1280x720 AAC].mp4` where 640_420 would be treated as resolution as well?

**Comment by Leslie-Wong-H** [comment]
First principal thinking, `640_420` is definitely not the episode number that aniep is designated to get.

**Comment by soruly** [comment]
I've re-written the resolution trimming regex in version 0.6.0. It should be able to handle this case now. You're filename has also been added to test case.

**Pull request closed without merging**
